$ANSIBLE_VAULT;1.1;AES256
36306436383933336137363436633866613865626566613264383236343335326263623563643338
3365333536613038323133383836666436386465663331660a323932383036613661393333326536
36336530306138653036393537376535313138333164306134323564656636396161643534616163
6639313630313738640a393331353566393934353932346263656162303333346165353535343563
30633661643231626464303831643266653730323033373861646636376139353935353533393536
31343433623337323338343364613830663366383534376639373565613266386666326465393239
31333164623935363234326436356131646332626534393830353035626263316430646463313861
38633636336639646636646364643836613836396630363336663266346363323138616466303061
3363
