apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ivolve
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==       # root
  MYSQL_DATABASE: aXZvbHZl           # ivolve
  MYSQL_USER: aXZvbHZl               # ivolve
  MYSQL_PASSWORD: aXZvbHZlMTIz       # ivolve123

