---
# tasks file for mysql

- name: Install MySQL server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Ensure MySQL service is running and enabled
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: Set MySQL root password
  ansible.builtin.mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    priv: "*.*
#SPDX-License-Identifier: MIT-0
---
# tasks file for mysql
